version: '3'
services:
  app:
    ports:
      - 3000:3000
    volumes:      
      - ./kit:/app/kit
      - ./src:/app/src
      - ./static:/app/static
      - ./package.json:/app/package.json
    command: npm run dev
    build:
      dockerfile: ./kit/docker/Dockerfile-dev
      context: .